// <auto-generated />
using System;
using IaBak.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IaBak.Server.Migrations
{
    [DbContext(typeof(IaBakDbContext))]
    [Migration("20200703182725_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("IaBak.Server.ArchiveItem", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRedundancy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Priority")
                        .HasColumnType("REAL");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("IaBak.Server.ItemStorage", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateNotified")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "UserId");

                    b.ToTable("ItemStorage");
                });

            modelBuilder.Entity("IaBak.Server.RecentSuggestion", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SuggestionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "UserId");

                    b.ToTable("RecentSuggestions");
                });

            modelBuilder.Entity("IaBak.Server.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
